#! /bin/sh

# Autostart
xrandr --rate 75 &
xrdb -load $HOME/.config/.Xresources &
setxkbmap -option caps:escape &
dunst -conf $HOME/.config/dunst/dunstrc &
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill --randomize $HOME/stuff/wallpapers/* &
$HOME/.config/polybar/launch.sh &
# Workspaces
bspc monitor -d 1 2 3 4 5

# Other stuff
bspc config border_width         0
bspc config window_gap           6
bspc config split_ratio          0.618
bspc config top_padding          34
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#758ECD"
